# Setup
title:    t4tsuhiko.github.io
tagline:  A responsive theme for your project on GitHub Pages
baseurl:  ""
paginate: 3

# About/contact
author:
  name:   Author name
  url:    https://t4tsuhiko.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-tactile

permalink: /:title.html
