# Setup
title:    celavis.github.io
tagline:  A responsive theme for your project on GitHub Pages
baseurl:  ""
paginate: 3

# About/contact
author:
  name:   Author name
  url:    https://celavis.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
